Implement backend SCRAM auth
pg-sharding/spqr pull request #202
Opened 2023-07-10 13:57 UTC by EinKrebs

2023-07-10 16:11 UTC, reshke commented on pkg/auth/auth.go
>  		return shard.Send(&pgproto3.PasswordMessage{Password: berule.AuthRule.Password})
what about authFrontend() ? 

also, we can actually setup postgresql shard with scram auth in tests and run scram auth in CI....

2023-07-10 16:42 UTC, reshke commented
Also pleasse indicate in the documentation/readme that SCRAM is now supported 🦀️️️️️️🦀️️️️️️🦀️️️️️️

2023-07-11 17:00 UTC, EinKrebs commented
> Also pleasse indicate in the documentation/readme that SCRAM is now supported crab️️️️️crab️️️️️crab️️️️️

Where to write this? Do I need to create another .md file in docs/ or update existing?

2023-07-12 08:36 UTC, Denchick commented
> Where to write this? Do I need to create another .md file in docs/ or update existing?

I would suggest create a new section Authentication methods or something in Router.md file.

2023-07-12 08:54 UTC, reshke commented
So, basically scram test are the same as non-scram test with exception in auth process be each sql-file run? Maybe we can add unit test for this feature too? See https://github.com/pg-sharding/spqr/blob/master/test/authentification/auth_test.go

2023-07-12 09:05 UTC, EinKrebs commented
> So, basically scram test are the same as non-scram test with exception in auth process be each sql-file run? Maybe we can add unit test for this feature too? See https://github.com/pg-sharding/spqr/blob/master/test/authentification/auth_test.go

It seems rather hard to mock psql's behavior in unit tests, it's way easier to set up cluster in docker compose

2023-07-12 09:49 UTC, reshke approved these changes

2023-07-12 10:16 UTC, Denchick requested changes
Let's not test SCRUM in docker

2023-07-12 14:21 UTC, Denchick approved these changes

2023-07-12 14:32 UTC, merged