Update Router.md
pg-sharding/spqr pull request #210
Opened 2023-07-11 13:56 UTC by reshke

resolves https://github.com/pg-sharding/spqr/issues/201

2023-07-12 07:25 UTC, EinKrebs requested changes

2023-07-12 07:25 UTC, EinKrebs commented on docs/Router.md
> +All SPQR configurations can be written in json, yaml or toml format. See examples in [config-example](../example/) or [pkg/config/router.go](../pkg/config/router.go)
```suggestion
All SPQR configurations can be written in json, yaml or toml format. See examples in [this directory](../examples/) or [pkg/config/router.go](../pkg/config/router.go)
```

2023-07-17 08:57 UTC, Denchick approved these changes

2023-08-07 11:48 UTC, Denchick approved these changes

2023-08-07 11:54 UTC, EinKrebs approved these changes

2023-08-07 11:54 UTC, merged