Fix datarace with memqdb.go?
pg-sharding/spqr pull request #260
Opened 2023-08-03 09:20 UTC by nikifkon

Not sure how to write test on dataraces. This version at least fails if I remove locks.

2023-08-03 09:31 UTC, reshke commented
we need to run unit-tests with `-race`

2023-08-09 11:39 UTC, Denchick requested changes

2023-08-09 12:28 UTC, nikifkon commented on qdb/memqdb.go
> +	defer spqrlog.Zero.Debug().Str("key-range", id).Msg("memqdb: exit: lock key range")
Like with other methods, an error will pop up to the user console.

2023-08-10 14:12 UTC, Denchick approved these changes

2023-08-10 14:15 UTC, merged