add some checks to Unite in coordinator
pg-sharding/spqr pull request #275
Opened 2023-08-11 14:25 UTC by diPhantxm

* check shardID is the same on left and right key ranges
* check the UpperBound on the left key range matches LowerBound on the right key range

2023-08-11 18:21 UTC, Denchick requested changes

2023-08-11 18:21 UTC, Denchick commented on test/feature/spqr_test.go
> +	postgresqlQueryTimeout          = 7 * time.Second
Maybe 10 then? 😄

2023-08-11 18:21 UTC, Denchick commented on coordinator/provider/coordinator.go
> +		return fmt.Errorf("failed to unite key ranges in wrong order")
Maybe you should do it somehow?

2023-08-11 19:35 UTC, diPhantxm commented on test/feature/features/coordinator.feature
> +    failed to unite key ranges routing different shards
Why you think so?

2023-08-14 06:12 UTC, Denchick approved these changes

2023-08-14 06:12 UTC, merged