fix key range intersection checks
pg-sharding/spqr pull request #276
Opened 2023-08-14 15:09 UTC by diPhantxm

* added feature tests for adding intersecting key range
* fix adding existing krid by splitting
* fix moving key range to the same shardID

If you move key range to the same shardID, it will return an error with the following message: `ERROR:  ERROR: transaction identifier "sh2-krid4" is already in use (SQLSTATE 42710)`. So I thought it's kinda pointless to move to the same shard and added another check.

Also when adding a new key range, one case of ranges intersection was uncovered - when you add a key range that's inside another existing key range. Thus this key range is added, but they actually intersect.

2023-08-15 04:25 UTC, Denchick requested changes

2023-08-15 04:25 UTC, Denchick commented on coordinator/provider/coordinator.go
> +	if _, err := qc.db.GetKeyRange(ctx, req.Krid); err == nil {
You could make this check even before locking key range.

2023-08-15 04:25 UTC, Denchick commented on coordinator/provider/coordinator.go
> +		return nil
Its quite obvious but it would be nice to add some comments why

2023-08-15 04:25 UTC, Denchick commented on qdb/ops/ops.go
> +		if kr.CmpRangesLessEqual(keyRange.LowerBound, v.LowerBound) && kr.CmpRangesLess(v.LowerBound, keyRange.UpperBound) ||
Maybe its time to fix https://github.com/pg-sharding/spqr/pull/276/files#diff-6a2b55b44547e95606a78cb12f14a8009366673e342d5e813bcf2f4ff558f1fdR39

For example, qdb.GetKeyRange method is called twice

2023-08-15 04:25 UTC, Denchick commented on test/feature/features/coordinator.feature
> +    key range krid4 intersects with krid3 present in qdb
key range A intersects with key range B in QDB

2023-08-15 04:25 UTC, Denchick commented on qdb/ops/ops.go
> +		if kr.CmpRangesLessEqual(keyRange.LowerBound, v.LowerBound) && kr.CmpRangesLess(v.LowerBound, keyRange.UpperBound) ||
It would be cool to add some ASCII art here

2023-08-16 12:27 UTC, diPhantxm commented
When splitting, check that bound doesn't equal lower or upper bound of the key range, because then it will be one point, which is not possible with the open half-intervals

2023-08-17 12:10 UTC, Denchick approved these changes

2023-08-17 12:11 UTC, merged