Single coord
pg-sharding/spqr pull request #280
Opened 2023-08-17 10:20 UTC by debebantur

2023-08-17 11:23 UTC, reshke commented
>If coordinator moves to router host (https://github.com/pg-sharding/spqr/issues/279) this pr can be closed
This is not true. 
If coordinator run logic moves to separate router goroutine instead of own process, nothing changes.

2023-08-21 06:27 UTC, Denchick requested changes

2023-08-21 06:27 UTC, Denchick commented on qdb/etcdqdb.go
> +	//must be more or equal to 5
Why?

2023-08-21 06:27 UTC, Denchick commented on coordinator/provider/coordinator.go
> +// spqr router`s availability
// RunCoordinator side effect: it runs an asynchronous goroutine 
// that checks the availability of the SPQR router

2023-08-21 06:27 UTC, Denchick commented on coordinator/provider/coordinator.go
> +	LOCK:
the wat
Lets rewrite this method without using LOCK tag
Or just move TryCoordinatorLock to a separate method

2023-08-21 11:03 UTC, reshke commented
LGTM?

2023-08-22 08:13 UTC, Denchick approved these changes

2023-08-22 08:13 UTC, merged