Add docker container for generate protoc, mock, goyacc and regel
pg-sharding/spqr pull request #390
Opened 2024-01-11 13:12 UTC by CBists

To generate packages with the same versions for all users

2024-01-11 13:14 UTC, reshke commented
nice

2024-01-11 13:15 UTC, EinKrebs requested changes

2024-01-11 13:15 UTC, EinKrebs commented on docker-compose.yaml
> +            context: .
It's better not to include generator here, for it has no purpose. Better to use Docker directly in Makefile

2024-01-11 13:17 UTC, EinKrebs commented on docker/generator/Dockerfile
> +FROM spqr-base-image
Maybe use `golang` docker image here, not to install go manually

2024-01-12 11:19 UTC, EinKrebs requested changes

2024-01-12 11:19 UTC, EinKrebs commented on Makefile
> +	docker run --name spqr-generator-1 spqr-generator --rm
You need to remove `--rm` flag

2024-01-12 13:33 UTC, EinKrebs commented on Makefile
> +	docker run --name spqr-generator-1 spqr-generator --rm
Also add `docker container rm spqr-generator-1` to the end of `generate` target

2024-01-12 13:43 UTC, EinKrebs approved these changes

2024-01-15 07:40 UTC, closed without merging