Change error resp
pg-sharding/spqr pull request #415
Opened 2024-01-18 09:40 UTC by CBists

Replace fmt.Errorf to SpqrError

2024-01-19 10:41 UTC, Denchick requested changes

2024-01-19 10:41 UTC, Denchick commented on test/regress/tests/console/expected/add.out
> +ERROR:  Code: SPQRD. Name: failed to match any datashard. Description: unknown shard nonexistentshard.
Postgres-way:

```
ERROR: unknown shard 'nonexistentshard'
```

2024-01-19 10:41 UTC, Denchick commented on test/regress/tests/console/expected/add.out
> +ERROR:  Code: SPQRK. Name: Keyrange error. Description: key range krid2 already present in qdb.
Postgres-way: `ERROR: key range 'krid2' already present in QDB`

2024-01-19 10:41 UTC, Denchick commented on pkg/coord/adapter.go
> +	return spqrerror.NewSpqrError("addWorldShard not implemented", spqrerror.SPQR_UNEXPECTED)
return spqrerror.NewSpqrError("addWorldShard **is** not implemented", **spqrerror.SPQR_NOTIMPLEMENTED**)

2024-01-19 10:41 UTC, Denchick commented on qdb/ops/ops.go
>  	existDataspace, err := qdb.ListDataspaces(ctx)
```suggestion
	existedDataspaces, err := qdb.ListDataspaces(ctx)
	if err != nil {
		return err
	}
	exists := false
	for _, ds := range existedDataspaces {
		exists = ds.ID == rule.Dataspace
		if exists {
			break
		}
	}
	if !exists {
		return fmt.Errorf("try to add sharding rule link to a non-existent dataspace")
		return spqrerror.NewSpqrError("an attempt to add sharding rule in non-existent dataspace", rule.Dataspace, spqrerror.SPQR_NO_DATASPACE)
	}
```

2024-01-19 10:41 UTC, Denchick commented on qdb/ops/ops.go
> +		return spqrerror.NewSpqrError("try to add key range link to a non-existent dataspace", spqrerror.SPQR_COMPLEX_QUERY)
spqrerror.SPQR_NO_DATASPACE

2024-01-19 10:43 UTC, Denchick requested changes
Check out error messages (typos, grammar) and error codes

2024-01-22 08:01 UTC, Denchick commented on qdb/etcdqdb.go
> +			return nil, spqrerror.New("deadlines exceeded", spqrerror.SPQR_KEYRANGE_ERROR)
```suggestion
			return nil, spqrerror.New("lock key range deadlines exceeded", spqrerror.SPQR_KEYRANGE_ERROR)
```

2024-01-22 08:02 UTC, Denchick commented on qdb/etcdqdb.go
> +			return spqrerror.New("deadlines exceeded", spqrerror.SPQR_KEYRANGE_ERROR)
```suggestion
			return spqrerror.New("unlock key range deadlines exceeded", spqrerror.SPQR_KEYRANGE_ERROR)
```

2024-01-22 08:04 UTC, Denchick commented on qdb/etcdqdb.go
> +		return spqrerror.Newf(spqrerror.SPQR_COMPLEX_QUERY, "router with id %s already exists", r.ID)
spqrerror.SPQR_UNEXPECTED

2024-01-22 08:04 UTC, Denchick commented on qdb/etcdqdb.go
> +			return spqrerror.Newf(spqrerror.SPQR_COMPLEX_QUERY, "router with address %s already exists", r.Address)
Please check error codes below because there are too much mistakes here.

2024-01-22 09:02 UTC, CBists commented on test/regress/tests/console/expected/add.out
> +ERROR:  key range krid2 already present in qdb.
fmt.Errorf  of automatically adding a dot to the end, so it seems to me it would be better to keep this pattern

2024-01-23 07:07 UTC, Denchick approved these changes
Decided it is too hard to add unit tests that checks error response. LGTM

2024-01-23 07:08 UTC, merged