Drop sharding rule, add relation definitions to dataspace
pg-sharding/spqr pull request #416
Opened 2024-01-18 10:34 UTC by reshke

2024-01-18 11:04 UTC, EinKrebs commented
Consider deprecating sharding rules instead of dropping them

2024-01-18 11:05 UTC, reshke commented
sharding rules dropped from SQL api, however they still present in grpc API and in backend code

2024-01-18 11:26 UTC, EinKrebs approved these changes

2024-01-19 11:46 UTC, EinKrebs requested changes

2024-01-19 11:46 UTC, EinKrebs commented on router/qrouter/proxy_routing.go
> +		if
??

2024-01-19 12:22 UTC, EinKrebs commented on router/qrouter/proxy_routing.go
> +		if
Why if here?

2024-01-19 12:24 UTC, EinKrebs requested changes

2024-01-19 12:24 UTC, EinKrebs commented on router/qrouter/proxy_routing.go
> +		if
Incorrect if

2024-01-19 12:27 UTC, reshke commented on router/qrouter/proxy_routing.go
> +		if
yea...
just pushed a bunch of work

2024-01-21 22:01 UTC, reshke commented
I would like to propose to use only one bound in key range (lower one). To check if given key lays within given keyrange we will only have to check that given key is greater (>=) then KR bound and no other (greater) key range satisfies the same.

2024-03-21 05:08 UTC, EinKrebs commented
@reshke PR is obsolete, consider closing it

2024-09-19 09:26 UTC, closed without merging