Add rename dataspace to distribution and refactor relating code
pg-sharding/spqr pull request #455
Opened 2024-01-25 19:46 UTC by reshke

2024-01-26 06:11 UTC, Denchick requested changes

2024-01-26 06:11 UTC, Denchick commented on qdb/memqdb.go
> +	RelationDistribution map[string]string                   `json:"table_distribution"`
So, `relation` or `table`?

2024-01-26 11:56 UTC, reshke commented on examples/init.sql
> -ADD SHARDING RULE r1 COLUMNS w_id;
no reason

2024-01-26 11:57 UTC, reshke commented on pkg/models/distributions/distribution.go
> +	// column types to be used
no, they are defined, but not in use yet

2024-01-29 08:17 UTC, Denchick approved these changes

2024-01-29 08:20 UTC, merged