fix xproto
pg-sharding/spqr pull request #456
Opened 2024-01-29 08:27 UTC by reshke

2024-01-30 04:17 UTC, EinKrebs requested changes
Half the tests failed

2024-01-30 12:02 UTC, Denchick requested changes

2024-01-30 12:02 UTC, Denchick commented on router/relay/relay.go
> +				// Do not respond here with bind complete, as relay step should do itself
```suggestion
				// Do not respond with BindComplete, as the relay step should take care of itself.

```

2024-01-30 12:02 UTC, Denchick commented on router/relay/relay.go
> +						// send to client
```suggestion
						// send to the client
```

2024-01-30 12:02 UTC, Denchick commented on router/relay/relay.go
> +						// send to client
```suggestion
						// send to the client
```

2024-01-31 05:59 UTC, x4m approved these changes

2024-01-31 06:06 UTC, EinKrebs approved these changes

2024-01-31 06:27 UTC, Denchick approved these changes

2024-01-31 06:27 UTC, merged