Create Syntax.md
pg-sharding/spqr pull request #511
Opened 2024-02-20 16:56 UTC by Denchick

2024-02-21 11:11 UTC, EinKrebs requested changes

2024-02-21 11:11 UTC, EinKrebs commented on docs/Syntax.md
> +(2 rows)
There's no such method, appararently

2024-02-21 11:11 UTC, EinKrebs commented on docs/Syntax.md
> +- What tables are you query
```suggestion
- What tables do you query
```

2024-02-21 11:11 UTC, EinKrebs commented on docs/Syntax.md
> +- Which columns in each table should the router look
look on/look for

2024-02-21 11:11 UTC, EinKrebs commented on docs/Syntax.md
> +- The type of these columns
```suggestion
- Types of these columns
```

2024-02-21 11:11 UTC, EinKrebs commented on docs/Syntax.md
> +Let's create a distribution first:
Maybe it's better to describe various sharidng-related terms before showing an example?

2024-02-21 11:11 UTC, EinKrebs commented on docs/Syntax.md
> +(1 line)
```suggestion
demo=> CREATE DISTRIBUTION ds1 COLUMN TYPES integer;
         add distribution         
----------------------------------
 created distribution with id ds1
(1 row)
```

2024-02-21 11:11 UTC, EinKrebs commented on docs/Syntax.md
> +The next step is to specify a list of tables and columns. TODO how to make it smaller
```suggestion
The next step is to specify a list of tables and columns. Making it simpler is TBD
```

2024-02-21 11:11 UTC, EinKrebs commented on docs/Syntax.md
> +(1 line)
```suggestion
CREATE KEY RANGE krid1 FROM 1 ROUTE TO sh1 FOR DISTRIBUTION ds1;
         add key range          
--------------------------------
 created key range with bound 1
(1 row)
```

2024-02-21 11:11 UTC, EinKrebs commented on docs/Syntax.md
> +(1 row)
```suggestion
CREATE KEY RANGE krid2 FROM 11 ROUTE TO sh1 FOR DISTRIBUTION ds1;
          add key range          
---------------------------------
 created key range with bound 11
(1 row)
```

2024-02-21 11:11 UTC, EinKrebs commented on docs/Syntax.md
> +(1 line)
```suggestion
CREATE KEY RANGE krid3 FROM 21 ROUTE TO sh2 FOR DISTRIBUTION ds1;
          add key range          
---------------------------------
 created key range with bound 21
(1 row)
```

2024-02-21 11:16 UTC, Denchick commented on docs/Syntax.md
> +The next step is to specify a list of tables and columns. TODO how to make it smaller
just drop this todo

2024-02-22 07:59 UTC, x4m approved these changes

2024-02-26 06:52 UTC, merged