Add 'SHOW realtions' method to console #512
pg-sharding/spqr pull request #515
Opened 2024-02-22 09:53 UTC by EinKrebs

2024-02-22 09:53 UTC, EinKrebs commented
Resolves #512

2024-02-22 11:36 UTC, reshke commented on test/feature/features/memqdb.feature
> -    ADD KEY RANGE krid1 FROM 1 TO 10 ROUTE TO sh1 FOR DISTRIBUTION ds1;
why?

2024-02-22 14:19 UTC, Denchick requested changes

2024-02-22 14:19 UTC, Denchick commented on test/regress/tests/console/expected/show_relations.out
> +ERROR:  column unknown_param not exists.
`ERROR:  column unknown_param does not exist.`

2024-02-22 14:19 UTC, Denchick commented on pkg/clientinteractor/interactor.go
> +	i := 0
You don't need this

2024-02-26 07:21 UTC, Denchick approved these changes

2024-02-26 07:21 UTC, merged