Added new spqr-balancer
pg-sharding/spqr pull request #552
Opened 2024-03-14 09:46 UTC by EinKrebs

2024-03-20 11:01 UTC, munakoiso requested changes

2024-03-20 12:30 UTC, EinKrebs commented on balancer/provider/balancer.go
> +	counts[len(counts)-1] = min(keyCount-(moveCount-1)*config.BalancerConfig().KeysPerMove, config.BalancerConfig().KeysPerMove)
keyCount can exceed maxMoveCount*maxKeysPerMove,

2024-03-20 13:19 UTC, EinKrebs commented on balancer/provider/balancer.go
> +		conn, err := pgx.Connect(ctx, params.Host)
Only target shard is analyzed here, I guess it's not great to pass up on error here

2024-03-22 10:24 UTC, munakoiso approved these changes

2024-03-25 06:51 UTC, merged