Rewrite Lock/Delete key range ops to prevent deadlocks
pg-sharding/spqr pull request #575
Opened 2024-03-28 13:43 UTC by EinKrebs

2024-03-28 19:14 UTC, Denchick requested changes

2024-03-28 19:14 UTC, Denchick commented on qdb/memqdb.go
> +			success = false
you don't need `success` and `lockedKR`, just do `return spqrerror.Newf(spqrerror.SPQR_KEYRANGE_ERROR, "key range \"%s\" is locked", lockedKR)`

2024-03-28 19:14 UTC, Denchick commented on qdb/memqdb.go
>  	if lock, ok := q.Locks[id]; ok {
```
lock, ok := q.Locks[id];
if !ok {
    return nil // or error
}
if !lock.TryLock() {
    return spqrerror.Newf(spqrerror.SPQR_KEYRANGE_ERROR, "key range \"%s\" is locked", id)
}
defer lock.Unlock()

```

2024-03-29 09:02 UTC, EinKrebs commented on Makefile
> +	go test ./cmd/... ./pkg/... ./router/... ./coordinator/... ./yacc/console...
MemQDB test is the only one where we specifically test for races & deadlocks, it doesn't currently make sense with other tests

2024-03-29 09:05 UTC, EinKrebs commented on Makefile
> +	go test ./cmd/... ./pkg/... ./router/... ./coordinator/... ./yacc/console...
Also it slows tests down to repeat them 20 times

2024-03-31 17:14 UTC, reshke commented on Makefile
> +	go test ./cmd/... ./pkg/... ./router/... ./coordinator/... ./yacc/console...
why do we remove -race option?

2024-04-01 08:40 UTC, Denchick requested changes

2024-04-01 08:40 UTC, Denchick commented on Makefile
> +	go test ./cmd/... ./pkg/... ./router/... ./coordinator/... ./yacc/console...
> Also it slows tests down to repeat them 20 times

I thought it was a feature, not a bug. They are still fast enough

2024-04-01 09:22 UTC, EinKrebs commented on Makefile
> +	go test ./cmd/... ./pkg/... ./router/... ./coordinator/... ./yacc/console...
Tests other than MemQDB are essentially deterministic, there's no point of re-running them

2024-04-03 08:24 UTC, Denchick approved these changes

2024-04-03 08:35 UTC, merged