Fix memqdb feature flaps
pg-sharding/spqr pull request #582
Opened 2024-04-01 06:09 UTC by EinKrebs

2024-04-01 06:26 UTC, EinKrebs commented
Now we actually check if pgx connection is established by checking ping results

2024-04-01 08:35 UTC, Denchick requested changes

2024-04-01 08:35 UTC, Denchick commented on test/feature/spqr_test.go
> +		return nil, fmt.Errorf("postgres is unresponsive")
postgres is not responding ?

2024-04-02 19:34 UTC, reshke approved these changes

2024-04-03 06:36 UTC, Denchick approved these changes

2024-04-03 06:36 UTC, merged