better console messages
pg-sharding/spqr pull request #629
Opened 2024-04-20 10:40 UTC by IakimovNutria

[Issue 398](https://github.com/pg-sharding/spqr/issues/398). У SPQR роутера и координатора есть административная консоль, в которой можно настраивать правила шардирования. Настройка происходит в консоли в формате запрос->ответ, и сейчас эти ответы не очень user-friendly. Надо изменить формат сообщений.

2024-04-22 06:21 UTC, EinKrebs commented
Closes #398

2024-04-22 06:21 UTC, EinKrebs requested changes
Would you please fix feature tests?

2024-05-06 09:22 UTC, Denchick approved these changes
Thank you for your contribution!

2024-05-20 08:46 UTC, Denchick approved these changes

2024-05-20 08:50 UTC, EinKrebs approved these changes

2024-05-20 08:50 UTC, merged