GSS-API frontend auth - Kerberos
pg-sharding/spqr pull request #657
Opened 2024-05-11 15:36 UTC by NitroLine

2024-05-23 05:28 UTC, EinKrebs requested changes
Kerberos auth feature test failed

2024-05-24 10:04 UTC, EinKrebs approved these changes

2024-05-24 10:05 UTC, EinKrebs requested changes
^

2024-05-24 13:04 UTC, Denchick approved these changes

2024-05-24 13:09 UTC, EinKrebs approved these changes

2024-05-24 13:10 UTC, merged

2024-05-24 13:11 UTC, Denchick commented
Thank you for your contribution!