Add 'REDISTRIBUTE KEY RANGE' command
pg-sharding/spqr pull request #789
Opened 2024-10-23 06:56 UTC by EinKrebs

2024-10-28 12:17 UTC, Denchick requested changes
Great job!
- Please add a description to all methods in balancer.go and coordinator.go
- Please add TODOs to all new methods that you add
- Please add regress tests for redistribute commond (just to check syntax and output)
- Please add as much documentation as possible

2024-10-28 12:52 UTC, EinKrebs commented on yacc/console/yx_test.go
> +			query: "REDISTRIBUTE KEY RANGE kr1 TO sh2 BATCH SIZE 500",
It's not the purpose of this test, it only tests parser, thus will parse any integer constant

2024-10-28 12:57 UTC, EinKrebs commented on pkg/clientinteractor/interactor.go
> +func (pi *PSQLInteractor) RedistributeKeyRange(_ context.Context, stmt *spqrparser.RedistributeKeyRange) error {
Why do we need to verify that if all key range ids must be unique

2024-10-28 12:57 UTC, EinKrebs commented on pkg/clientinteractor/interactor.go
> +	if err := pi.WriteDataRow(fmt.Sprintf("redistribute key range '%s' to shard '%s' by batches of %d", stmt.KeyRangeID, stmt.DestShardID, stmt.BatchSize)); err != nil {
No need for distribution id here

2024-10-28 13:00 UTC, EinKrebs commented on balancer/provider/balancer.go
> -	host := shardFrom.TargetReplica
We are now using BatchMoveKeyRange method of the coordinator instead of creating move tasks in balancer

2024-10-28 13:03 UTC, EinKrebs commented on test/feature/spqr_test.go
> +		_, err := tctx.queryPostgresql(host, "SELECT 1", struct{}{}, postgresqlQueryTimeout)
Why do we need it here? Here the default timeout is sufficient

2024-11-12 15:35 UTC, Denchick requested changes
One suggestion: let's not use the hashlib extension. This is not a popular extension and a +1 dependency for our users. Let's discuss this at a regular meeting.

Overall, excellent work!

2024-11-12 15:35 UTC, Denchick commented on test/feature/features/redistribute.feature
> +  Scenario: REDISTRIBUTE KEY RANGE works with multiple moves
> +376
> I just hope there is no typo in this feature file

2024-11-13 04:09 UTC, EinKrebs commented on test/regress/tests/router/sql/hash_routing.sql
> +INSERT INTO xx (col1) VALUES ('0');
`众口难调` is not actually meant to route on the second shard, whilst `0` is

2024-11-13 10:56 UTC, EinKrebs commented on test/feature/features/balancer.feature
> +    /spqr/spqr-balancer --config /spqr/test/feature/conf/balancer_all_keys.yaml > /balancer.log
The last key range is actually moved to another shard

2024-11-13 10:57 UTC, EinKrebs commented on test/feature/features/balancer.feature
> +    /spqr/spqr-balancer --config /spqr/test/feature/conf/balancer_all_keys.yaml > /balancer.log
kr5 is moved to sh2 and united with kr6

2024-11-13 11:33 UTC, EinKrebs commented on pkg/models/kr/keyrange.go
> -	// now this works only for unidim distributions
It's not needed, discussed with @reshke

2024-11-14 10:00 UTC, Denchick approved these changes

2024-11-14 11:06 UTC, merged