Drop some dead code
pg-sharding/spqr pull request #828
Opened 2024-11-19 22:03 UTC by Denchick

2024-11-20 05:01 UTC, rkhapov approved these changes

2024-11-20 05:16 UTC, reshke requested changes

2024-11-20 05:16 UTC, reshke commented on pkg/client/clientpool.go
> -	Shutdown() error
https://github.com/pg-sharding/spqr/blob/707d5121afee287e40996b08989cb97907099403/router/client/client.go#L1024

2024-11-20 15:28 UTC, reshke approved these changes

2024-11-20 15:45 UTC, reshke approved these changes

2024-11-20 15:47 UTC, merged

2024-11-29 09:25 UTC, EinKrebs commented
PR was reverted due to the following error in coordinator_show.feature:
```
--- Failed steps:

  Scenario: show clients works # features/coordinator_show.feature:74
    And SQL result should match json # features/coordinator_show.feature:80
      Error: actual value doesn't match expected at path '.0'
Expected:
[
    {
        "dbname":"regress",
        "router_address":"regress_router:7000",
        "user":"regress"
    },
    {
        "dbname":"regress",
        "router_address":"regress_router:7000",
        "user":"regress"
    },
    {
        "dbname":"regress",
        "router_address":"regress_router_2:7000",
        "user":"regress"
    },
    {
        "dbname":"regress",
        "router_address":"regress_router_2:7000",
        "user":"regress"
    }
]
But was:
[{"client_id":"824635998848","dbname":"regress","router_address":"local","server_id":"no backend connection","user":"regress"},{"client_id":"824635998848","dbname":"regress","router_address":"local","server_id":"no backend connection","user":"regress"}]
, actual value doesn't match expected at path '.0'
```

2024-11-29 09:25 UTC, EinKrebs commented
@Denchick FYI